name: Build
run-name: ${{ github.actor }} is building ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # - run: echo "ğŸ–¥ï¸ At workspace ${{ github.workspace }}."
      - run: sudo apt-get update -y
      # - run: sudo apt-get install make
      - run: sudo apt-get install -y rpm rpmlint alien
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Build the rpm and covert to deb
        run: make
      # - name: Run some version commands
      #   run: |
      #     echo "ğŸ’¡ cargo --version ..."
      #     cargo --version
      #     echo "ğŸ’¡ rustup --version ..."
      #     rustup --version
      #     echo "ğŸ’¡ curl --version ..."
      #     curl --version
      - run: echo "ğŸ This job's status is ${{ job.status }}."
